### ISSUE TITLE
custom swc options do not work

### ISSUE THREAD

**Issue by andrei-markeev** [noyobo/esbuild-plugin-es5#2]
## Current Behavior

"Support custom swc options" is marked as completed in the README, but it doesn't really work.

I did a small investigation, and I think the problem is that `deepmerge` call at https://github.com/noyobo/esbuild-plugin-es5/blob/main/src/index.ts#L42 is incorrect. Deepmerge doesn't mutate the `transformOptions`, instead, it returns a new object.

so the correct usage would be `transformOptions = deepmerge(transformOptions, options?.swc)` rather than just `deepmerge(transformOptions, options?.swc)`

from the [documentation](https://github.com/TehShrike/deepmerge#mergex-y-options) of `deepmerge`:

> Merging creates a new object, so that neither x or y is modified.

## Expected Behavior

Custom swc options are supported.

## Environment

- Version: 2.0.0
- Platform: Win
- Node.js Version: 18.16.0

**Comment by noyobo** [comment]
v2.0.1 fixed
